display_set_gui_size(960, 540)
if (obj_player.show_gui == 1)
{
    draw_set_color(c_white)
    draw_set_font(font)
    draw_sprite_ext(spr_flyingpep, image_index, 280, 110, 2, 2, 0, c_white, 1)
    draw_text(200, 95, global.player_coin)
}
with (obj_player)
{
    if (show_gui == 1)
    {
        if (charselect == 1)
        {
            if (global.player_hp == 7)
                draw_sprite_ext(spr_player_HP, 0, 120, 100, 1, 1, 0, c_white, 1)
            else if (global.player_hp == 6)
                draw_sprite_ext(spr_player_HP, 2, 120, 100, 1, 1, 0, c_white, 1)
            else if (global.player_hp == 5)
                draw_sprite_ext(spr_player_HP, 4, 120, 100, 1, 1, 0, c_white, 1)
            else if (global.player_hp == 4)
                draw_sprite_ext(spr_player_HP, 6, 120, 100, 1, 1, 0, c_white, 1)
            else if (global.player_hp == 3)
                draw_sprite_ext(spr_player_HP, 8, 120, 100, 1, 1, 0, c_white, 1)
            else if (global.player_hp == 2)
                draw_sprite_ext(spr_player_HP, 10, 120, 100, 1, 1, 0, c_white, 1)
            else if (global.player_hp == 1)
                draw_sprite_ext(spr_player_HP, 12, 120, 100, 1, 1, 0, c_white, 1)
        }
        /*if (charselect == 2)
        {
            if (global.player_hp == 7)
                draw_sprite_ext(spr_player2_HP, 0, 120, 120)
            else if (global.player_hp == 6)
                draw_sprite_ext(spr_player2_HP, 1, 120, 120)
            else if (global.player_hp == 5)
                draw_sprite_ext(spr_player2_HP, 2, 120, 120)
            else if (global.player_hp == 4)
                draw_sprite_ext(spr_player2_HP, 3, 120, 120)
            else if (global.player_hp == 3)
                draw_sprite_ext(spr_player2_HP, 4, 120, 120)
            else if (global.player_hp == 2)
                draw_sprite_ext(spr_player2_HP, 5, 120, 120)
            else if (global.player_hp == 1)
                draw_sprite_ext(spr_player2_HP, 6, 120, 120)
        }*/
        if (global.player_rage == 7)
            draw_sprite_ext(spr_player_RAGE, 7, 120, 100, 1, 1, 0, c_white, 1)
        else if (global.player_rage == 6)
            draw_sprite_ext(spr_player_RAGE, 6, 120, 100, 1, 1, 0, c_white, 1)
        else if (global.player_rage == 5)
            draw_sprite_ext(spr_player_RAGE, 5, 120, 100, 1, 1, 0, c_white, 1)
        else if (global.player_rage == 4)
            draw_sprite_ext(spr_player_RAGE, 4, 120, 100, 1, 1, 0, c_white, 1)
        else if (global.player_rage == 3)
            draw_sprite_ext(spr_player_RAGE, 3, 120, 100, 1, 1, 0, c_white, 1)
        else if (global.player_rage == 2)
            draw_sprite_ext(spr_player_RAGE, 2, 120, 100, 1, 1, 0, c_white, 1)
        else if (global.player_rage == 1)
            draw_sprite_ext(spr_player_RAGE, 1, 120, 100, 1, 1, 0, c_white, 1)
        else if (global.player_rage == 0)
            draw_sprite_ext(spr_player_RAGE, 0, 120, 100, 1, 1, 0, c_white, 1)
    }
    draw_text(10, 10, state)
}


