with (obj_player)
{
    if (show_gui == 1)
    {
        if (charselect == 1)
        {
            if (global.player_hp == 7)
                draw_sprite(spr_player_HP, 0, 100, 100)
            else if (global.player_hp == 6)
                draw_sprite(spr_player_HP, 2, 100, 100)
            else if (global.player_hp == 5)
                draw_sprite(spr_player_HP, 4, 100, 100)
            else if (global.player_hp == 4)
                draw_sprite(spr_player_HP, 6, 100, 100)
            else if (global.player_hp == 3)
                draw_sprite(spr_player_HP, 8, 100, 100)
            else if (global.player_hp == 2)
                draw_sprite(spr_player_HP, 10, 100, 100)
            else if (global.player_hp == 1)
                draw_sprite(spr_player_HP, 12, 100, 100)
        }
        if (charselect == 2)
        {
            if (global.player_hp == 7)
                draw_sprite(spr_player2_HP, 0, 100, 100)
            else if (global.player_hp == 6)
                draw_sprite(spr_player2_HP, 1, 100, 100)
            else if (global.player_hp == 5)
                draw_sprite(spr_player2_HP, 2, 100, 100)
            else if (global.player_hp == 4)
                draw_sprite(spr_player2_HP, 3, 100, 100)
            else if (global.player_hp == 3)
                draw_sprite(spr_player2_HP, 4, 100, 100)
            else if (global.player_hp == 2)
                draw_sprite(spr_player2_HP, 5, 100, 100)
            else if (global.player_hp == 1)
                draw_sprite(spr_player2_HP, 6, 100, 100)
        }
        if (global.player_rage == 7)
            draw_sprite(spr_player_RAGE, 7, 100, 100)
        else if (global.player_rage == 6)
            draw_sprite(spr_player_RAGE, 6, 100, 100)
        else if (global.player_rage == 5)
            draw_sprite(spr_player_RAGE, 5, 100, 100)
        else if (global.player_rage == 4)
            draw_sprite(spr_player_RAGE, 4, 100, 100)
        else if (global.player_rage == 3)
            draw_sprite(spr_player_RAGE, 3, 100, 100)
        else if (global.player_rage == 2)
            draw_sprite(spr_player_RAGE, 2, 100, 100)
        else if (global.player_rage == 1)
            draw_sprite(spr_player_RAGE, 1, 100, 100)
        else if (global.player_rage == 0)
            draw_sprite(spr_player_RAGE, 0, 100, 100)
    }
    draw_text(10, 10, state)
}


